### ISSUE TITLE
Assemble video string outs

### ISSUE THREAD

**Issue by thoward** [sensu/sensu-enterprise-workshop#126]
- [x] Lesson 1
- [ ] Lesson 2 _(waiting on issue #127)_
- [x] Lesson 3 _(waiting on issue #128)_
- [x] Lesson 4 _(waiting on issue #129)_
- [ ] Lesson 5 _(waiting on issue #130)_
- [ ] Lesson 6 _(waiting on issue #131)_
- [ ] Lesson 7 _(waiting on issue #132)_
- [ ] Lesson 8 _(waiting on issue #133)_
- [ ] Lesson 9 _(waiting on issue #134)_
- [ ] Lesson 10 _(waiting on issue #135)_
- [ ] Lesson 11 _(waiting on issue #136)_
- [ ] Lesson 12 _(waiting on issue #137)_
